export const COUNTRY_STATES: Record<string, string[]> = {
  Afghanistan: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  Albania: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier"],
  Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  Angola: ["Luanda", "Huambo", "Lobito", "Benguela", "Kuito"],
  Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Tucumán", "Santa Fe", "Salta"],
  Australia: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "ACT", "Northern Territory"],
  Austria: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barishal"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Liège", "Bruges"],
  Benin: ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Bohicon"],
  Bolivia: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Paraná", "Rio Grande do Sul", "Pernambuco", "Ceará", "Amazonas"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya"],
  Cameroon: ["Yaoundé", "Douala", "Bamenda", "Bafoussam", "Garoua", "Maroua"],
  Canada: ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia", "New Brunswick"],
  Chad: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo"],
  Chile: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  China: ["Beijing", "Shanghai", "Guangdong", "Zhejiang", "Jiangsu", "Sichuan", "Henan", "Hubei", "Hunan"],
  Colombia: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga"],
  Congo: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo"],
  "Cote d'Ivoire": ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "San-Pédro", "Korhogo"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  "DR Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu"],
  Ecuador: ["Quito", "Guayaquil", "Cuenca", "Ambato", "Manta"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Luxor", "Aswan"],
  Ethiopia: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Hawassa", "Bahir Dar"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  France: ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie", "Hauts-de-France", "Normandy", "Brittany"],
  Gambia: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"],
  Germany: ["Bavaria", "North Rhine-Westphalia", "Baden-Württemberg", "Berlin", "Hamburg", "Hesse", "Saxony", "Brandenburg"],
  Ghana: ["Greater Accra", "Ashanti", "Western", "Eastern", "Central", "Northern", "Volta", "Brong-Ahafo"],
  Greece: ["Attica", "Central Macedonia", "Thessaly", "Western Greece", "Crete", "Peloponnese"],
  Guinea: ["Conakry", "Kankan", "Kindia", "Labé", "N'Zérékoré"],
  Hungary: ["Budapest", "Debrecen", "Miskolc", "Pécs", "Győr"],
  India: ["Maharashtra", "Uttar Pradesh", "Tamil Nadu", "Karnataka", "Gujarat", "West Bengal", "Rajasthan", "Andhra Pradesh", "Kerala", "Delhi"],
  Indonesia: ["Jakarta", "West Java", "East Java", "Central Java", "Banten", "Sumatra Utara", "Sulawesi Selatan"],
  Iran: ["Tehran", "Isfahan", "Fars", "Khorasan Razavi", "East Azerbaijan", "Mazandaran"],
  Iraq: ["Baghdad", "Basra", "Nineveh", "Erbil", "Sulaymaniyah", "Kirkuk"],
  Ireland: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  Israel: ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod"],
  Italy: ["Lombardy", "Lazio", "Campania", "Sicily", "Veneto", "Piedmont", "Emilia-Romagna", "Tuscany"],
  Japan: ["Tokyo", "Osaka", "Kanagawa", "Aichi", "Hokkaido", "Fukuoka", "Hyogo", "Saitama"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba", "Karak"],
  Kazakhstan: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Nyeri"],
  Kuwait: ["Kuwait City", "Hawalli", "Ahmadi", "Farwaniyah", "Jahra"],
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  Libya: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Zawiya"],
  Madagascar: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga"],
  Malawi: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
  Malaysia: ["Kuala Lumpur", "Selangor", "Johor", "Penang", "Perak", "Sabah", "Sarawak", "Kedah"],
  Mali: ["Bamako", "Sikasso", "Mopti", "Koulikoro", "Kayes"],
  Mauritania: ["Nouakchott", "Nouadhibou", "Rosso", "Kiffa", "Kaédi"],
  Mexico: ["Mexico City", "Jalisco", "Nuevo León", "Estado de México", "Veracruz", "Puebla", "Guanajuato", "Chihuahua"],
  Morocco: ["Casablanca", "Rabat", "Fez", "Marrakesh", "Agadir", "Tangier", "Meknes", "Oujda"],
  Mozambique: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  Myanmar: ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  Nepal: ["Bagmati", "Madhesh", "Gandaki", "Lumbini", "Karnali", "Sudurpashchim"],
  Netherlands: ["North Holland", "South Holland", "Utrecht", "North Brabant", "Gelderland"],
  "New Zealand": ["Auckland", "Wellington", "Canterbury", "Waikato", "Bay of Plenty", "Otago"],
  Niger: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
  Nigeria: [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue",
    "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu",
    "FCT - Abuja", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina",
    "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo",
    "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"
  ],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Kristiansand"],
  Pakistan: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Islamabad", "Gilgit-Baltistan"],
  Peru: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Cusco"],
  Philippines: ["Metro Manila", "Cebu", "Davao", "Calabarzon", "Central Luzon", "Western Visayas"],
  Poland: ["Masovian", "Lesser Poland", "Silesian", "Greater Poland", "Lower Silesian", "Łódź"],
  Portugal: ["Lisbon", "Porto", "Braga", "Setúbal", "Aveiro", "Coimbra"],
  Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal"],
  Romania: ["Bucharest", "Cluj", "Iași", "Timișoara", "Constanța"],
  Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Chelyabinsk"],
  Rwanda: ["Kigali", "Southern Province", "Northern Province", "Eastern Province", "Western Province"],
  "Saudi Arabia": ["Riyadh", "Mecca", "Medina", "Jeddah", "Dammam", "Tabuk", "Khobar"],
  Senegal: ["Dakar", "Thiès", "Diourbel", "Saint-Louis", "Tambacounda", "Kaolack"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  Singapore: ["Central Region", "East Region", "North Region", "North-East Region", "West Region"],
  Somalia: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Beledweyne"],
  "South Africa": ["Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Limpopo", "Mpumalanga", "Free State", "North West", "Northern Cape"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Gyeonggi"],
  "South Sudan": ["Juba", "Wau", "Malakal", "Yei", "Bor"],
  Spain: ["Madrid", "Catalonia", "Andalusia", "Valencia", "Galicia", "Basque Country", "Castile and León"],
  "Sri Lanka": ["Western", "Central", "Southern", "Northern", "Eastern", "North Western", "Sabaragamuwa"],
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
  Syria: ["Damascus", "Aleppo", "Homs", "Hama", "Latakia"],
  Tanzania: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya"],
  Thailand: ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai"],
  Togo: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Palimé"],
  Tunisia: ["Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana"],
  Uganda: ["Kampala", "Nansana", "Kira", "Ssabagabo", "Mbarara"],
  Ukraine: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah", "Al Ain", "Ajman"],
  "United Kingdom": ["London", "Birmingham", "Leeds", "Glasgow", "Sheffield"],
  "United States": ["California", "Texas", "Florida", "New York", "Pennsylvania", "Illinois", "Ohio", "Georgia", "North Carolina", "Michigan"],
  Uruguay: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras"],
  Uzbekistan: ["Tashkent", "Namangan", "Samarkand", "Andijan", "Bukhara"],
  Vanuatu: ["Port Vila", "Luganville", "Norsup", "Isangel", "Lénakel"],
  Venezuela: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  Vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho"],
  Yemen: ["Sana'a", "Aden", "Taiz", "Al Hudaydah", "Ibb"],
  Zambia: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola"],
  Zimbabwe: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Epworth"],
};
